# Generated by Django 3.1.2 on 2020-11-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesscard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscard',
            name='inquiry_date',
            field=models.DateTimeField(blank=True, verbose_name='마지막 조회일'),
        ),
    ]
