# Generated by Django 3.1.2 on 2020-11-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesscard', '0003_auto_20201104_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscard',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='이름'),
        ),
    ]
