"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path
from rest_framework import ISO_8601

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ROOT_DIR = os.path.dirname(BASE_DIR)
# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "avcim2+6v8_k(sy#hq4j3cno*%9+ya-c)ojjcmsvpfefqs%y@v"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
ALLOWED_HOSTS = [
    "businesscard.koreacentral.cloudapp.azure.com",
    "businesscard.koreacentral.cloudapp.azure.com:8000",
    "https://testsennaazurefunc.azurewebsites.net",
]
# Application definition
# Add package (corsheaders, rest_framework, rest_framework, rest_framework.authtoken, rest_auth) / 2020-10-15 robert
# Add App (businesscard, businesscardbook, businesscardocr, groupbusinesscard, notice) / 2020-10-15 robert

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",  # add package
    "rest_framework",  # add package
    "rest_framework.authtoken",  # add package
    "rest_auth",  # add package
    "django.contrib.sites",  # add package
    "allauth",  # add package
    "allauth.account",  # add package
    "allauth.socialaccount",  # add package
    "rest_auth.registration",  # add package
    "django_filters",  # add package
    "businesscard",  # add app
    "businesscardbook",  # add app
    "businesscardocr",  # add app
    "groupbusinesscard",  # add app
    "notice",  # add app
]

REST_FRAMEWORK = {  # DRF SETTING
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "UNICODE_JSON": True,
    "UPLOADED_FILES_USE_URL": True,
    "DATE_FORMAT": ISO_8601,
    "DATE_INPUT_FORMATS": [ISO_8601],
    "DATETIME_FORMAT": ISO_8601,
    "DATETIME_INPUT_FORMATS": [ISO_8601],
    "TIME_FORMAT": ISO_8601,
    "TIME_INPUT_FORMATS": [ISO_8601],
}

SITE_ID = 1

ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_EMAIL_REQUIRED = True

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # add package
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases


DATABASES = {
    "default": {
        "ENGINE": "sql_server.pyodbc",
        "NAME": "deexkorea2",
        "USER": "deexkorea2",
        "PASSWORD": "deex2020$",
        "HOST": "deexbc2.database.windows.net",
        "PORT": "1433",
        "OPTIONS": {
            "driver": "ODBC Driver 17 for SQL Server",
            "MARS_Connection": True,
            "driver_supports_utf8": True,
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# frontend server domain
CORS_ORIGIN_ALLOW_ALL = False
CORS_ORIGIN_WHITELIST = [
    "http://businesscard.koreacentral.cloudapp.azure.com",
    "http://businesscard.koreacentral.cloudapp.azure.com:8000",
    "https://testsennaazurefunc.azurewebsites.net",
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "ko-kr"
# django 2.2.17은 "ko-kr"
# LANGUAGE_CODE = "ko"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_L10N = False

USE_TZ = False

DATE_FORMAT = "Y-m-d"

DATETIME_FORMAT = "Y-m-d H:i:s"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_DIR = os.path.join(BASE_DIR, "static")
STATICFILES_DIRS = [
    STATIC_DIR,
]
STATIC_ROOT = os.path.join(ROOT_DIR, ".static_root")
# Media files (Images, files) Create / 2020-10-15 robert

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
OCRIMAGE_URL = "https://testsennaazurefunc.azurewebsites.net/api/HttpExample?gubun=1&image_url="
PROJECT_URL = "http://businesscard.koreacentral.cloudapp.azure.com:8000"
